### ISSUE TITLE
Review: Running EMG Example

### ISSUE THREAD

**Issue by BKillen05** [pyomeca/pyomeca#106]
Using the instructions on the repository I could not view the figures without first importing pyplot from matplotlib. Not sure if this was only a problem for me. System/Anaconda spec : Python 3.6.10, Windows 10 Enterprise, 64-bit

**Comment by romainmartinez** [comment]
Hello @BKillen05 and thanks for the issue.

`pyomeca`'s documentation uses [Jupyter notebooks](https://jupyter.org/) to show code and instructions.
If you use the server we provide [here](https://mybinder.org/v2/gh/pyomeca/pyomeca/master?filepath=notebooks), the figures appear correctly.
This process is quite standard and other libraries use it in their documentation: [`scikit-learn`](https://scikit-learn.org/stable/visualizations.html) (42k stars on GitHub), [`pandas`](https://pandas.pydata.org/docs/user_guide/10min.html#plotting) (26k stars on GitHub) or [`xarray`](http://xarray.pydata.org/en/stable/plotting.html) (1.7k stars on GitHub).
Under the hood, pyomeca uses `matplotlib`.
To show a figure in a non notebook environment, the user just has to add `plt.show()`.

**Comment by BKillen05** [comment]
Hello @romainmartinez 
Thank you for your reply.  I was running the example on a standalone anaconda environment not the Jupyter notebook you indicated. This is likely the problem as you say. It's possible I missed this but it is worth double checking this is documented
