### ISSUE TITLE
troubles with xarrays and findpeaks

### ISSUE THREAD

**Issue by Dareczin** [pyomeca/pyomeca#120]
Hello everyone,

I tried to get resultant velocity from Markers data manually, as I cannot find proper method in docs. By bypass it worked and I got similar results to previous pyomeca versions, but output is still in xarray, while findpeaks from scipy is only for 1d data. I tried to put it into pandas, but still there are errors, that I do not fully understand. 

I placed the notebook in the attachment.
[przyspieszenie.zip](https://github.com/pyomeca/pyomeca/files/5772147/przyspieszenie.zip)

Or maybe there is a method to read c3d as it was in the previous versions? 

Best regards,
Darek

**Comment by pariterre** [comment]
Hi there,
find_peaks should work as soon as you have a one-d data. As I sent you via email, this should work :)
```python
from pyomeca import Markers
from scipy.signal import find_peaks

data = Markers.from_c3d('your_c3d.c3d')
peaks, _ = find_peaks(data.sel(channel="name_of_the_channel"), height=10)
```
If you want to do this for all the channel you can use a for loop (as in the snippet I sent you)
```python
from pyomeca import Markers
from scipy.signal import find_peaks

# Load data
data = Markers.from_c3d('B0346_dollyo_pilka_P.c3d').meca.norm(dim="axis")/1000

# For all the channels
for channel in data_diff.channel.data:
    # Get a reference to the data
    data_selected = data.sel(channel=channel)
    
    # Find peaks
    peaks, _ = find_peaks(data_selected, height=10)

    # Do want you want with the peaks
```
See you

**Comment by pariterre** [comment]
@Dareczin 
Will you need more assistance? :)

**Comment by Dareczin** [comment]
Sorry i should close the issue

pon., 11 sty 2021, 05:42 użytkownik Pariterre <notifications@github.com>
napisał:
