### ISSUE TITLE
Slicing data using the square brackets

### ISSUE THREAD

**Issue by pariterre** [pyomeca/pyomeca#122]
Hello!

Would that makes sense to allow slicing using text, instead of requiring to access via `isel`? 
For instance, `a["x", "marker1", :]` would call in the background `return a.isel(...)` 
I think it would make things much easier for someone who is not accustomed to xarray. If I recall well, we discussed this already, but I don't recall the reason not to do it. Recently I helped someone who did not know how to use xarrays precisely for the reason (and I must admit, I had to browse on internet myself quite a lot to perform what feels to be very simple tasks such a slicing data). 

In terms of changes, I think it would be very minimal, but would greatly help the community!

**Comment by romainmartinez** [comment]
It is already possible to do this: `markers.loc["x", "markers1", :]`.
Here, `loc` refers to a selection by label.

`xarray` already allows many indexing routines that cover most use cases, see [here](https://xarray.pydata.org/en/stable/indexing.html).

These can be summarized here :

| Dimension lookup | Index lookup | Syntax            |
|-------------------------|-----------------|------------|
| Positional       | By integer   | `d[:, 0]`                    |
| Positional       | By label     | `d.loc[:, 'IA']`            |
| By name          | By integer   | `d.isel(space=0)`    |
| By name          | By label     | `d.sel(space='IA')`  |
