### ISSUE TITLE
How to install Pyomeca from the Pycharm Terminal for Win 10.

### ISSUE THREAD

**Issue by jrdunga** [pyomeca/pyomeca#124]
I apologize for my very easy question but I am beginner. I can use pyomeca in google colab but I can not install pyomeca in my computer. I use win 10 and I am try practice with the Pycharm. I believe that Pycharm has a venv, I dont know if this change anything . 

I already tried:

count install -c count-forge pyomeca
conda install -c conda-forge/label/cf202003 pyomeca

I waited to long time but when a try:

import pyomeca

I receive in return:

" Traceback (most recent call last):
   File "<input>", line 1, in <module>
   File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
     module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'pyomeca'. "

or 

"TypeError: Parameters to generic types must be types. Got NotImplemented."

I think that library pyomeca was installed mas but I not can import. 

If anybody can help me.
Regards.

**Comment by pariterre** [comment]
Dear @jrdunga 

The command is:
```
conda install -c conda-forge pyomeca
```

Cheers!

**Comment by jrdunga** [comment]
Sorry! 

Where I wrote "count" in:

"count install -c count-forge pyomeca"

I should have written "conda". 

But I will try again. 
Thanks.

**Comment by jrdunga** [comment]
When I try again:

conda install -c conda-forge pyomeca

I receve in return:

"(venv) C:\Users\jrdun\OneDrive\Documentos\Scripts>conda install -c conda-forge pyomeca
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort."

**Comment by pariterre** [comment]
It seems there are conflicting versions for the dependencies. Did you install something else? If yes, did you do it for this particular project or for another one. If for another, I would suggest to separate project in different environments. Python is highly sensitive to package versions and this can create this kind of issues.
If the extra dependencies are for this project, you can try to install pyomeca prior to the other dependencies. Sometime the order we install things prevents from installing.
If it still does not work, you will have to install by hand (copy the Pyomeca repo and use the command `python setup install.py` after navigating to the Pyomeca folder)

**Comment by jrdunga** [comment]
This is my first project. I am really begginer my first "hello, world" was little while ago kkkk. So I can unistall anything if necessery. I already tried unistall and reinstall my Anaconda and my Pycharm but I still have the same problem. What you recomend? Install only Miniconda? Anaconda? Add in the PATH? Or install only Python 3.9? This make any difference?

Thanks for your attention and patience.

**Comment by jrdunga** [comment]
And I think that Pycharm create venv automatically but I am not sure.

**Comment by pariterre** [comment]
Technically you don't have to uninstall anything. Anaconda is an environment manager, meaning that you can create separate working environment for each of your project which are completely independent to each other. You may have to erase a specific environment from time to time (using the conda commands), but not the whole installation. I strongly recommend against installing anything in the `base` environment. Create a specific environment for each of your project and then configure pycharm to point to it. `venv` is another environment manager, you cannot mix them.

**Comment by jrdunga** [comment]
Now I can import pyomeca now.

Thank you very much.

When the paper is ready pyomeca will be in references. I have no doubts.

Once again my thanks

**Comment by jrdunga** [comment]
I dont know if I can do another question in this same topic, so if I am doing something wrong I apologize.

Now I am with a problem in open c3d data in directory with accent. Is there any way to acess a c3d data in a path with accent?

For exemple, if I try:


import pyomeca
path1 = "C:\Dunga\Física\Biomecânica\Doc\Dados\RANDOM\Data\s2 (1).c3d"
m =  pyomeca.Markers.from_c3d(path1)


I recive in retorn

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\jrdun\anaconda3\envs\venvt\lib\site-packages\pyomeca\markers.py", line 392, in from_c3d
    return read.read_c3d(
  File "C:\Users\jrdun\anaconda3\envs\venvt\lib\site-packages\pyomeca\io\read.py", line 22, in read_c3d
    reader = ezc3d.c3d(f"{filename}").c3d_swig
  File "C:\Users\jrdun\anaconda3\envs\venvt\lib\site-packages\ezc3d\__init__.py", line 127, in __init__
    self.c3d_swig = ezc3d.c3d(path)
  File "C:\Users\jrdun\anaconda3\envs\venvt\lib\site-packages\ezc3d\ezc3d.py", line 1680, in __init__
    _ezc3d.c3d_swiginit(self, _ezc3d.new_c3d(*args))
OSError: Could not open the c3d file: iostream stream error



but if I try the same in directory without accent everything work rigth

For exemple:


import pyomeca
path2 = "C:\Dunga\Fisica \Biomecanica\Doc\Dados\RANDOM\Data\s2 (1).c3d"
m =  pyomeca.Markers.from_c3d(path2)


I can open the data.

Furthermore, I can open another data in the path1 (with accent) if my data not be .c3d

For exemple, if I try:

path1 = "C:\Dunga\Física\Biomecânica\Doc\Dados\RANDOM\Data\text.txt"
arv = open(path1) 

everything work rigth.

 Is there any way to acess a c3d data in a path with accent?

I thanks once again.

**Comment by pariterre** [comment]
Hi @jrdunga !
Ideally, it is better to separate issues, but don't worry about it right now :)

The question you ask is not related to pyomeca, but seems to be related to ezc3d, which is an external dependency. Fortunately, I am the programmer of ezc3d 😁 if it turns out to be a hard problem, I may ask you that we move the discussion in an issue in ezc3d.

The first thing I will say, is path parsing is a hard problem. It greatly depends on the OS you are running on and therefore the coding you are using (the 20 different iso-, utf8, utf16, etc.), which escape characters you are using, etc. In brief, it is a mess... especially on Windows..

My first try would be to replace the backslashes with forward slashes ("\" for "/"). In general (meaning on any software even outside pyomeca), I would never use "\" in path because on Windows, "\" is also an escape character. 
If it does not help, my second advice would be to remove any special characters. That is because if we manage to make a patch that works on your computer, it will break something on other computers. Again, in general, my advice, if any files (even outside of ezc3d) has a tiny chance of ever be to be used on a Windows system, I would never use special characters at all, including spaces. 

Hope this helps

**Comment by jrdunga** [comment]
I managed to solve this problem enabling utf8 like in https://consignor.zendesk.com/hc/en-us/articles/360016886479-Errors-caused-by-Windows-10-Unicode-UTF-8-encoding. I think it will work only in my win10 but I want to shared this answer becouse maybe help another person.

Thank you again.
