### ISSUE TITLE
Dependencies error

### ISSUE THREAD

**Issue by pariterre** [pyomeca/pyomeca#125]
The command :
`conda install pyomeca -cconda-forge`
install pyomeca using Python 3.7 on Linux. But this version conflict with more recent version of numpy (or typing). 

The fix is to force the install of python 3.9 after having installed pyomeca:
`conda install python=3.9 -cconda-forge`
But this is not elegant. The version 3.9 should be added to anaconda
@romainmartinez are you up to it? Or should I have a look?

**Comment by romainmartinez** [comment]
> The command :
> `conda install pyomeca -cconda-forge`
> install pyomeca using Python 3.7 on Linux. But this version conflict with more recent version of numpy (or typing)

When [pyomeca is installed with python 3.7](https://github.com/pyomeca/pyomeca/runs/2925465537?check_suite_focus=true), numpy 1.21.0 is installed, which seems to be [the latest public release](https://pypi.org/project/numpy/#history).
What is the conflict you mentioned?

> The fix is to force the install of python 3.9 after having installed pyomeca:
> `conda install python=3.9 -cconda-forge`
> But this is not elegant. The version 3.9 should be added to anaconda

Pyomeca works with any version of python >= 3.6 (including 3.9), so I think I'd rather leave the choice to the user than force a specific version.

**Comment by pariterre** [comment]
I tried reinstalling from a new environment as I did before:
```bash
conda create -n new_env
conda activate new_env
conda install python -cconda-forge
python
import pyomeca
```
and it now works, while the last time I did that actually failed at the `import pyomeca` because of an fstring in numpy (that is incompatible with python 3.7). I am not sure why two different outcomes occurred... I'll close the issue for now since it seems to work!

**Comment by romainmartinez** [comment]
> and it now works, while the last time I did that actually failed at the import pyomeca because of an fstring in numpy (that is incompatible with python 3.7).

This seems unlikely as f-string were introduced in python 3.6 and we do not support < 3.6. Anyway, feel free to reopen if this issue remains.  :)

**Comment by pariterre** [comment]
Yup, but there are new ways to use them introduced earlier, for instance:
```python
val = 2
f"{val=}"
```
will produce the output
`"val = 2"`
which is very neat, but is not compatible with earlier versions of python

**Comment by romainmartinez** [comment]
Ah, got it! :+1:
