### ISSUE TITLE
delsys c3d

### ISSUE THREAD

**Issue by SebastienCordillet** [pyomeca/pyomeca#131]
Hi, Thanks you so much for pyomeca. 
For an ex-user of Matlab like me, your solution is very easy to use and very useful for my daily use in python while I mainly work with inertial unit data.
Actually, I have some troubles to import data from c3d generated by Delsys File Utility (hpf to c3d). Channel names contain specific characters (colon and dot) which cause errors during import. It's possible to fix this bug by manual renaming channels but I search a solution to avoid this time-consuming manipulation.

**Comment by romainmartinez** [comment]
Hello and thanks for the feedback!

Can you share the traceback so we can better identify if the problem comes from pyomeca or ezc3d?

Also, have you tried playing with the `prefix_delimiter` and `prefix_delimiter` options (see [here](https://pyomeca.github.io/api/markers/#pyomeca.markers.Markers.from_c3d) for an example)?

**Comment by SebastienCordillet** [comment]
Yeas I tried `prefix_delimiter` and `suffix_delimiter` but nothing worked. 

The traceback
![image](https://user-images.githubusercontent.com/39163740/170952550-d9c93fbb-9e21-47d1-94f0-6cc4c9566662.png)

and  labels of analogs channels (from Mokka) : 
![image](https://user-images.githubusercontent.com/39163740/170953328-76777c47-ea6f-495a-a381-3c90ad373bcd.png)

Thanks for your feedback.

**Comment by pariterre** [comment]
I feel the problem is not the channel but the "rate" which is equal to zero?
@romainmartinez Do you remember if the rate is the one from the point, because if it is taken from the Header, it is. Since it is pure analog data, maybe delsys did not fill that information properly...

**Comment by SebastienCordillet** [comment]
Thanks @pariterre for your feedback.
I have same troubles when I use only ezc3d. If the bug come from framerate, why it's fix when I change manually channel names in Mokka?

**Comment by SebastienCordillet** [comment]
Thanks for suggestion. You are right, rewritting using Mokka fix the bug.
