### ISSUE TITLE
Recover the trajectory color

### ISSUE THREAD

**Issue by hasnaaouadoudibelabzioui** [pyomeca/pyomeca#135]
Hi, 

I would like to express my gratitude for creating this helpful library.

 I have a question regarding whether it's possible to use your library to retrieve the color of a marker. 

Thank you for taking the time to respond to my question.

**Comment by pariterre** [comment]
Allo Hasnaa :) 
You are very welcome! 
To be sure, what do you mean by "color of a marker". I suspect it means "the color of the markers in Nexus" (or another acquisition software). It it is the case, `pyomeca` is currently unavailable to retrieve the metadata from a C3D file. However, you can access them using `ezc3d` which is the backend C3D reader (i.e. if you have pyomeca installed, you necessarily have ezc3d installed). You can have a look at the documentation for navigating an ezc3d structure. I am not sure where this information is stored in the c3d file, but I would suspect it is in. 

Assuming you are using python, it would look something like this (untested code):
```python
import ezc3d

c = ezc3d('PATH_TO_FILE')
print(c['parameters']['POINT']['color']['value']
```
I suggest that you are printing the keys of 'parameters' and 'POINT' dictionnaries to see all the options!

Hope this helps!

**Comment by hasnaaouadoudibelabzioui** [comment]
Thank you so much for reponding to me. After trying what you suggested, the 'color' parameter is not in the ezc3d library.

**Comment by pariterre** [comment]
If you can't find this value in the ezc3d, then it means it is not saved in the c3d file. Meaning it is internal structure of Nexus (or whatever software you are using). This means that is is not possible to get this information as they don't provide it..

**Comment by hasnaaouadoudibelabzioui** [comment]
Thank you so muche for your response !
