### ISSUE TITLE
conflicting sizes for dimension 'channel': length 272 on the data but length 255 on coordinate 'channel'

### ISSUE THREAD

**Issue by PressGO** [pyomeca/pyomeca#136]
The issue arises when my labels are >255, which C3D would create new meta data in the form of LABELS2.

I tried appending LABELS2 to LABELS in the metadata, but it seems that the c3d wasn't able to write? (i used ezc3d for this)

**Comment by pariterre** [comment]
Dear @PressGO 

The LABELS2 stuff should be dealt internally, so you should not have to manually separate them. 
What do you mean exaclty by "dimension channel" vs "coordinate channel"?

Can you confirm which version of ezc3d is installed?

**Comment by PressGO** [comment]
I am using the conda build version of ezc3d 1.5.9. 

Unfortunately, i have that many markers as i also have implements and things like that for my marker set. I realize the issue is the c3d formatting as they max out at 256, which i assume is 32 bytes of data for a set of LABEL. I manage to load the data in btk though, i assume VICON or MOKKA handles this by reading the PARAMETERs and treats them as the same thing? not too sure but, pyomeca wasn't able to do this for when i tried instantiating the marker object. 

Is there a work around for pyomeca with respect to this?

**Comment by pariterre** [comment]
Can you try to import you data using ezc3d directly (without the pyomeca overlay)? I want to know if it is a pyomeca issue or a ezc3d issue, as ezc3d should not have problems dealing with more than 255 markers, while I have no idea for pyomeca as its delevelopment has been staled for a while now...

**Comment by PressGO** [comment]
Alright. i will get back to you asap

**Comment by PressGO** [comment]
It seems you are right, ezc3d managed to load the all the marker data. Thanks! I assume if i needed the labels i would have to get LABEL and LABEL2.

**Comment by pariterre** [comment]
Yes, LABEL2 is the continuity of LABEL :)
