### ISSUE TITLE
Markers.from_trc -> IndexError: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by anboen** [pyomeca/pyomeca#138]
First thank you for this comprehensive library. It works perfectly with c3d files!
When i use trc files i always encounter  a IndexError("single positional indexer is out-of-bounds") error.

I initially thought that Vicon exports the file wrongly but i got the same behaviour through Mokka exports.

Is this a known error?

**Comment by pariterre** [comment]
Dear @anboen 
The main developer of pyomeca has left from quite some time now, and noone has actually taken the project from where he left it (as part of the team, I am focused on biorbd, bioptim and ezc3d). I was also part of the original crew of pyomeca but it was drastically changed for the second version. All that to say I would be the person to answer the best your solution and I would have to dig into a code I know nothing about to answer... My best guess is to try to fix the issue and open a pull request if you do so, I still have the admin rights in this project to accept new PR.

**Comment by anboen** [comment]
Dear @pariterre 
Thanks a lot for your answer and also for your amazing work! 
I think i will build a hack and use the csv reader for this file-type.
