### ISSUE TITLE
Publish on PyPi

### ISSUE THREAD

**Issue by bernikr** [pyomeca/pyomeca#140]
Now that the ezc3d dependency is avalible on pypi (pyomeca/ezc3d#343) it would be great if this package could be published as well. As this is pure python this should hopefully be easy.

Thx in advance

**Comment by pariterre** [comment]
Done in #141 
Please confirm this work (confirmed on Linux so far :) )

**Comment by bernikr** [comment]
Can confirm it works on windows as well

Finally i can get rid of conda for my current project^^

Thank you so much
