### ISSUE TITLE
PyTest

### ISSUE THREAD

**Issue by pariterre** [pyomeca/pyomeca#20]
The created environment as it is proposed in packaging for dev won't work because there is missing dependencies

Here is the error message : 
ImportError: cannot import name 'MappingProxyType'

NOTE : This happened on two different computers

**Comment by romainmartinez** [comment]
I think it's because we have a file called "types.py". Can you try to rename it and restart?

I never had this error.

**Comment by romainmartinez** [comment]
I think that the error comes from your Pycharm configuration. Your Pycharm interpreter should be `miniconda3/envs/pyomeca/bin/python` and not `miniconda3/envs/pyomeca/bin/python3`.

**Comment by romainmartinez** [comment]
I had the `MappingProxyType` error this morning ... rename the folder `types` in `obj` solved my problem.
