### ISSUE TITLE
getting columns from labels

### ISSUE THREAD

**Issue by Dareczin** [pyomeca/pyomeca#60]
Hi!

I am still noob, but since last correspondence with Pariterre, I had tons of other work so I am getting back to your library. Last time I successfully imported my file

import pyomeca
c = pyomeca.Markers3d.from_c3d('B0264_dollyo_air_P_T01.c3d')
c.get_labels

but then I stuck.  from the labels i am interested in marker called RTOE. I tried to get values from it by c['RTOE'] but is wrong. 

I would like to mention that I read examples but I cannot do anything from it. Please give me a hints, I am not here to have ready working code, just some directions. Eventually, is there any specific command to get velocity values for specific marker by some commands?

Best regards,
Darek

**Comment by pariterre** [comment]
Hi @Dareczin 
I am not sure if we have implemented such an accessor... I might give it a try tomorrow. Still it won't be in a release version for the next weeks or so. 
So right now, the easiest way I see to get a specific marker is to find its index in number format. So from get_label, you find the indexes you are interested in, and from now, you can slice the data (c is actually an upgraded numpy so it can be used like so, the lines being XYZ1 components, the columns being the markers and the 3rd dimension the time frames.
So sometime like this should do the trick :
```python
import pyomeca
c = pyomeca.Markers3d.from_c3d('my_c3d.c3d')
idx = [i for i, name in enumerate(c.get_labels) if name == 'my_marker_name']
c[:, idx, :]
```

@romain have you already implemented a ```get_index(name)``` function? Otherwise I will just copy what I suggested.
Also do you think adding the capability to write index in labels into c[:, (text1, text2), :] should be considered (if even possible?)

**Comment by Dareczin** [comment]
Hi!

Lesson learned, but then I got another problem. I also would like to apologise, because last time I did not explore tutorials enough.

I simplified your hint:

import numpy as np
import pandas as pd
import pyomeca
rtoe = pyomeca.Markers3d.from_c3d('B0264_dollyo_air_P_T01.c3d', names = ['RTOE'])

ten i add

print(rtoe)
print(f"2d labels: {rtoe.get_2d_labels()}")
print(f"time frame: {rtoe.get_time_frames}")

and results regarding time is bothering

[[[-235.46638489 -235.4675293  -235.46890259 ... -239.62644958
   -239.62660217 -239.6272583 ]]

 [[-284.62969971 -284.62567139 -284.62091064 ... -299.20880127
   -299.22290039 -299.23828125]]

 [[  43.74824524   43.74737167   43.74677658 ...   43.97157669
     43.9798851    43.98918152]]

 [[   1.            1.            1.         ...    1.
      1.            1.        ]]]
2d labels: ['RTOE_X', 'RTOE_Y', 'RTOE_Z']
time frame: [0.0000e+00 4.0000e-03 8.0000e-03 ... 1.3520e+01 1.3524e+01 1.3528e+01]

Thanks to you I managed to turn numpy arrays into pandas series

rtoex = rtoe[0,0]
rtoey = rtoe[1,0]
rtoez = rtoe[2,0]

dfx = pd.Series(rtoex)
dfy = pd.Series(rtoey)
dfz = pd.Series(rtoez)

df = pd.concat([dfx, dfy, dfz], axis =1)

And I get nice table for x,y,z values. But to compute velocity I need time. Values should be larger by 0.002 s for each row as I import text file from Mokka software.  How do I append timeframe to be as in attached example in txt?
[B0295_Ap_air_L (1).txt](https://github.com/pyomeca/pyomeca/files/3374833/B0295_Ap_air_L.1.txt)

**Comment by pariterre** [comment]
Hi there!
I'll @romainmartinez answer your question since he uses more pandas than me. But while you wait for his answer, I suggest that you have a look at the ```to_dataframe()``` method that in my understanding construct and return a pandas series from the values!

**Comment by Dareczin** [comment]
The point is I do not know how to call timeframe from this marker and while calling it as I present it did not show me float type numbers, and it ts not [3,0] array neither.  Just the information about how to call array about dataframe will be sufficient. Then I will try to to deriative functions to compute velocity.

**Comment by romainmartinez** [comment]
Hi @Dareczin 

This is the code snippet you are looking for:

```python
data_path = "data.c3d"
markers = ["RTOE"]

m = (
    Markers3d.from_c3d(data_path, names=markers)
    .to_dataframe(add_metadata=["get_time_frames"])
)
```
Which gives

```
      RTOE_X      RTOE_Y      RTOE_Z  get_time_frames
0  32.572296 -243.140488  676.574524             0.00
1  32.571041 -243.140732  676.580994             0.01
2  32.564896 -243.133316  676.577209             0.02
3  32.575111 -243.139709  676.575439             0.03
4  32.588200 -243.136124  676.574463             0.04
```

**Comment by Dareczin** [comment]
Thank you for your effort, but unfortunetly I got this: I have notebook in the folder with c3d file so i do this:
import pandas as pd
import pyomeca

markers = ["RTOE"]

m = (
    pyomeca.Markers3d.from_c3d( "B0264_dollyo_air_P_T01.c3d", names=markers)
    .to_dataframe(add_metadata=["get_time_frames"])
)

without pyomeca befre Markers 3d it cannot find it

but then I got his error 

ValueError                                Traceback (most recent call last)
<ipython-input-5-0a38148ee8ff> in <module>
      8 m = (
      9     pyomeca.Markers3d.from_c3d( "B0264_dollyo_air_P_T01.c3d", names=markers)
---> 10     .to_dataframe(add_metadata=["get_time_frames"])
     11 )

~\Anaconda3\lib\site-packages\pyomeca\frame_dependent.py in to_dataframe(self, add_metadata)
    330             else:
    331                 cols.update({imeta: ivalue})
--> 332         return pd.DataFrame(self.to_2d(), columns=self.get_2d_labels()).assign(**cols)
    333 
    334     def to_csv(self, file_name, header=False):

~\Anaconda3\lib\site-packages\pandas\core\frame.py in assign(self, **kwargs)
   3549         if PY36:
   3550             for k, v in kwargs.items():
-> 3551                 data[k] = com.apply_if_callable(v, data)
   3552         else:
   3553             # <= 3.5: do all calculations first...

~\Anaconda3\lib\site-packages\pandas\core\frame.py in __setitem__(self, key, value)
   3368         else:
   3369             # set column
-> 3370             self._set_item(key, value)
   3371 
   3372     def _setitem_slice(self, key, value):

~\Anaconda3\lib\site-packages\pandas\core\frame.py in _set_item(self, key, value)
   3443 
   3444         self._ensure_valid_index(value)
-> 3445         value = self._sanitize_column(key, value)
   3446         NDFrame._set_item(self, key, value)
   3447 

~\Anaconda3\lib\site-packages\pandas\core\frame.py in _sanitize_column(self, key, value, broadcast)
   3628 
   3629             # turn me into an ndarray
-> 3630             value = sanitize_index(value, self.index, copy=False)
   3631             if not isinstance(value, (np.ndarray, Index)):
   3632                 if isinstance(value, list) and len(value) > 0:

~\Anaconda3\lib\site-packages\pandas\core\internals\construction.py in sanitize_index(data, index, copy)
    517 
    518     if len(data) != len(index):
--> 519         raise ValueError('Length of values does not match length of index')
    520 
    521     if isinstance(data, ABCIndexClass) and not copy:

ValueError: Length of values does not match length of index

**Comment by Dareczin** [comment]
I cannot send you this c3d file here for checkup, unless I do it on your mail. Github did not suppport it and its 16 mb per file.  I there any other way to call metadata array and then convert it into pandas series? Or do you wish me to send the file to you. From tutorials I assume that you focused more on emg anlysis and my problems are not yet expoled in a manner of c3d files.

**Comment by pariterre** [comment]
Hi @Dareczin,
You can send me the file via mail (I think you already have it). I can quickly check the problem!

**Comment by pariterre** [comment]
@Dareczin,
The code you gave me (plus a ```print``` I added):
```python
import pandas as pd
import pyomeca

markers = ["RTOE"]
m = (
pyomeca.Markers3d.from_c3d( "B0264_dollyo_air_P_T01.c3d", names=markers)
.to_dataframe(add_metadata=["get_time_frames"])
)

print(m)
```
combined with the c3d file seems to work just fine here. It returns: 
```
          RTOE_X      RTOE_Y     RTOE_Z  get_time_frames
0    -235.466385 -284.629700  43.748245            0.000
1    -235.467529 -284.625671  43.747372            0.004
2    -235.468903 -284.620911  43.746777            0.008
3    -235.470474 -284.615356  43.746460            0.012
...
3381 -239.626450 -299.208801  43.971577           13.524
3382 -239.626602 -299.222900  43.979885           13.528
3383 -239.627258 -299.238281  43.989182           13.532

[3384 rows x 4 columns]
```
Which seems the expected results to me... Which version of pyomeca and ezc3d are installed? If you installed them using the command ```conda install pyomeca -cconda-forge``` you can easily update them: ```conda update pyomeca ezc3d```.

Cheers

**Comment by Dareczin** [comment]
Thanks! Updating versions solved this issue. Now I get to computing
velocity....

Best wishes
Darek

śr., 10 lip 2019 o 10:20 Pariterre <notifications@github.com> napisał(a):

**Comment by pariterre** [comment]
@Dareczin 
For your information, thanks to your intuitive way of using pyomeca, I added different ways to access stuff. For example, soon you will be able to get markers directly from their name like so:
```python
import pyomeca
c = pyomeca.Markers3d.from_c3d('my_lovely_c3d_file.c3d')
print(c[:, 'my_first_marker', :])
```
and even mix numbers and marker names:
```python
print(c[:, [0, 1, 'my_second_marker'], :])
```
Hope this will make things easier! 

This will come in the next release, so stay tuned!

**Comment by Dareczin** [comment]
I am glad that I am not only burden for you:)

I will be watching and waiting for updates

czw., 11 lip 2019 o 17:22 Pariterre <notifications@github.com> napisał(a):
