### ISSUE TITLE
Make pyomeca installable anywhere

### ISSUE THREAD

**Issue by romainmartinez** [pyomeca/pyomeca#66]
- [x] conda
- [ ] pip
- [ ] setup.py [NO TESTED]

**Comment by pariterre** [comment]
Pyomeca is already hosted on conda-forge. Is that the purpose of the tick (meaning that conda is already done but not pip?
Also, since we removed the automatic incrementations of version, we must find a way to remind ourselves to do it time to time

**Comment by romainmartinez** [comment]
> Um.... we could include a quick example to redirect people to biorbd, do product placement and show potential. But I don't think we should be exhaustive with the

Yep!

> Also, since we removed the automatic incrementations of version, we must find a way to remind ourselves to do it time to time

Will think about that
