### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by romainmartinez** [pyomeca/pyomeca#67]
On [readthedocs](https://readthedocs.org/).

**Comment by romainmartinez** [comment]
We need to find interesting examples to include in the documentation and potentially in the paper

**Comment by pariterre** [comment]
Should this include or not the use of biorbd?

**Comment by romainmartinez** [comment]
Um.... we could include a quick example to redirect people to `biorbd`, do "product placement" and show the potential. But I don't think we should be exhaustive with the `biorbd` features.

What do you think?

**Comment by pariterre** [comment]
Yep, that sounds good. Being exhaustive with *biord* would be too long anyway :)

I'll have to write its own example and generate proper documentation later for it
