### ISSUE TITLE
computing distance between markers

### ISSUE THREAD

**Issue by Dareczin** [pyomeca/pyomeca#79]
Hi!

I am wondering about the possibility to use this library to compute distance between two markers. In the mokka, only option is to create graph, but no possibility to export the data. I do not have such data from original research, so I want to collect a data from distance between two markers like shoulder and finger.

Best regards,
Darek

**Comment by pariterre** [comment]
Hi Darek,
Assuming you have your data loaded using Markers3d, then simply subtracting two marker positions gives you the distance between them. If you want the Euclidian distance, then you can compute the norm between them (Pythagorian theorem). For instance:
```python
from pyomeca import Markers3d
data = Markers3d.from_c3d('path/to/c3d.c3d')
distance = data['name_marker1'] - data['name_maker2']  # You can also reference the markers using data[:, idx, :] where idx is the number of the marker
norm_distance = distance.norm()
print(norm_distance)
```
See you

**Comment by Dareczin** [comment]
Thank you, works perfectly, the same with mokka graph

Best regards
Darek

śr., 11 wrz 2019 o 14:01 Pariterre <notifications@github.com> napisał(a):
