### ISSUE TITLE
writing to csv problem

### ISSUE THREAD

**Issue by Arevis13** [pyomeca/pyomeca#87]
Hello,
I'm new to programming and github so I'm not sure if this is the correct place to ask this question, but I have a problem with converting my file from c3d to csv. I edited one of the examples and got rid of the errors and it seems to be working fine but after you take a look at the values they are totally incorrect. Anyone have idea what is wrong and how to repair this? As you can see below, for example y value should be around 100 but in a csv it is starting from 67.
(I'm including the code, the screenshot from motionbuilder where you can see the trajectory and values in the original file and a screenshot from a fragment of a created csv file)

`from pathlib import Path

from pyomeca import Markers3d, Analogs3d

# Path to data
DATA_FOLDER = Path(r"C:\Users\Dom\Desktop\mggr\koncowe") 
#MARKERS_CSV = DATA_FOLDER / "markers.csv"
MARKERS_C3D = DATA_FOLDER / "calosc_aktor_z_mieczem.c3d"
#ANALOGS_CSV = DATA_FOLDER / "analogs.csv"

markers_4 = Markers3d.from_c3d(MARKERS_C3D, idx=[0, 1, 2, 3])

markers_4.to_csv(r"C:\Users\Dom\Desktop\mggr\koncowe\atest.csv", header=True)`

![image](https://user-images.githubusercontent.com/60902272/74195493-9d1ed580-4c5b-11ea-9428-131b534a5519.png)
![image](https://user-images.githubusercontent.com/60902272/74195713-27673980-4c5c-11ea-9abc-da34810a3b5f.png)

**Comment by romainmartinez** [comment]
Hi @Arevis13,
It's hard to solve your issue without having access to the data. You can send me a c3d file to my email address (martinez.staps@gmail.com) so I can take a look at it.

**Comment by Arevis13** [comment]
Hi,
Here is a c3d file I'm using, the marker on the screenshot was Hip-1.
Thanks in advance

pon., 10 lut 2020 o 23:43 Romain Martinez <notifications@github.com>
napisał(a):

**Comment by romainmartinez** [comment]
You did not send me your file

**Comment by Arevis13** [comment]
I'm pretty sure it's in the attachment (see pic). Anyway, whatever the
reason you didn't see it I'm attaching it again, plus in zip file and a
google disc link to avoid further problems.

https://drive.google.com/file/d/1YIzbSQTxrUnpSpHvtHzCQkTL_Hk2pDRW/view?usp=sharing

[image: image.png]

wt., 11 lut 2020 o 15:39 Romain Martinez <notifications@github.com>
napisał(a):

**Comment by pariterre** [comment]
@romainmartinez 
If it is okay for, I'll let you have a look. But if it is ezc3d related, ping me, I'll solve this :D

**Comment by romainmartinez** [comment]
Okay, I looked at your file and got the same values:

```python
import matplotlib.pyplot as plt

from pyomeca import Markers3d

data_path = "calosc_aktor_z_mieczem.c3d"
markers = Markers3d.from_c3d(data_path, names=["phantom_I_-Hip-1"])

markers.plot()
plt.show()
```
![test](https://user-images.githubusercontent.com/17710617/74353486-f8e67d00-4d87-11ea-9933-ecfc9c0c81de.png)

Of all your markers, the following markers have their first 10 values between 90 and 110:

```python
[
    "phantom_I_-Chest-1_Y",
    "phantom_I_-Chest-4_X",
    "phantom_I_-LHand-3_Y",
    "phantom_I_-RShoulder-1_X",
]
```
@pariterre, either the file was written incorrectly or there is a problem with `ezc3d`:

```python
import ezc3d

c3d = ezc3d.c3d("calosc_aktor_z_mieczem.c3d")
c3d["data"]["points"][1, 0, :]  # 67.81333923,   67.81333923,   67.81333923, ...
```

**Comment by romainmartinez** [comment]
Closing
