### ISSUE TITLE
Averaged rototrans bug

### ISSUE THREAD

**Issue by romainmartinez** [pyomeca/pyomeca#91]
As discussed in #88, there's some weird behavior on this `Rototrans.from_averaged_rototrans()` that could be the result of a bug.

## Environment setup

```bash
git clone git@github.com:romainmartinez/pyomeca.git
cd pyomeca
conda env create
conda activate pyomeca
pip install -r requirements-dev.txt
```

## Reproducible example

```python
import numpy as np

from pyomeca import Angles, Rototrans

size = (3, 1, 100)

def test_rt_mean(rt, seq="xyz"):
    rt_mean = Rototrans.from_averaged_rototrans(rt)

    angles_mean = Angles.from_rototrans(rt_mean, seq).isel(time=0)
    angles_mean_ref = Angles.from_rototrans(rt, seq).mean(dim="time")

    np.testing.assert_array_almost_equal(angles_mean, angles_mean_ref, decimal=2)
```

This works
```python
angles = Angles(np.random.rand(*size))
seq = "xyz"
rt = Rototrans.from_euler_angles(angles, seq)
test_rt_mean(rt)
```

this does not work
```python
rt = Rototrans.from_random_data(size=size)
test_rt_mean(rt)
```

Which is the equivalent of
```python

angles = Angles.from_random_data(size=size)
seq = "xyz"
rt = Rototrans.from_euler_angles(angles, seq)
test_rt_mean(rt)
```

`from_random_data()` is implemented as follows:
```python
Angles(np.random.normal(*size).cumsum(-1))
```

Can you take a look at this @pariterre?

**Comment by pariterre** [comment]
This is not supposed to work : 
```
def test_rt_mean(rt, seq="xyz"):
    rt_mean = Rototrans.from_averaged_rototrans(rt)

    angles_mean = Angles.from_rototrans(rt_mean, seq).isel(time=0)
    angles_mean_ref = Angles.from_rototrans(rt, seq).mean(dim="time")

    np.testing.assert_array_almost_equal(angles_mean, angles_mean_ref, decimal=2)
```

If it was that easy to mean a matrix, we would not need to have a proper function.
The reason the first one works, is by chance (probably that using random directly from euler creates matrices that are near from each other). 

This is there intended not to work

**Comment by pariterre** [comment]
And the reason they behave differently, which seems surprising at first, is that 
```
angles = Angles(np.random.rand(*size))
```
does not produce the same as this:
```
Angles.from_random_data(distribution, size=(3, 1, size[-1]), **kwargs)
```
which is in the `from_random_data` from Rototrans

**Comment by romainmartinez** [comment]
> This is not supposed to work.
I made the implementation based on [this test](https://github.com/pyomeca/pyomeca/blob/715daffa5f821dca392b33fe937dcf442e4e832e/tests/test_rototrans.py#L143). What is the difference here?

**Comment by romainmartinez** [comment]
> And the reason they behave differently, which seems surprising at first, is that
does not produce the same as this:


Yes, I am aware of that, but in the end it's just random angles and it should work both ways?

**Comment by pariterre** [comment]
As I said, meaning Euler angles will be wronger as angles grow. 
```python
angles = Angles(np.random.rand(*size))
np.min(angles, axis=2)
np.max(angles, axis=2)
``` 
will return values between 0-1 while the random constructor of Rototrans:
```python
angles = Angles.from_random_data(distribution, size=(3, 1, size[-1]))
np.min(angles, axis=2)
np.max(angles, axis=2)
```
will return values apparently ranging from -20 to 20 (from a quick simulation I made printing the values).

**Comment by romainmartinez** [comment]
Ah ok gotcha @pariterre!
The `cumsum` in the `from_random_data` increases the angles too much.

So, as I understand it, our implementation may be good but not the test?

**Comment by pariterre** [comment]
That is correct. I don't think there is error in the implementation, but the test won't work as is... A test with know values would do the trick or to use the first implementation (with much smaller angles)
