### ISSUE TITLE
RT last line should be checked

### ISSUE THREAD

**Issue by romainmartinez** [pyomeca/pyomeca#92]
During RT creation this should be checked:

```python
data[3, :3, :] = 0
data[3, 3, :] = 1
```

I started the following implementation:

```python
# Make sure last line reads [0, 0, 0, 1]
zeros = data[3, :3, :]
ones = data[3, 3, :]
if not np.alltrue(zeros == 0) or not np.alltrue(ones == 1):
    some_zeros = np.random.choice(zeros.ravel(), 5)
    some_ones = np.random.choice(ones.ravel(), 5)
    raise ValueError(
        "Last line does not read [0, 0, 0, 1].\n"
        f"Here are some values that should be 0: {some_zeros}\n"
        f"And others that should 1: {some_ones}"
    )
```

But I get errors on the from_transposed_rototrans, from_averaged_rototrans and from_markers methods, in both versions of pyomeca (v1 and v2).

Are these two lines necessary in your opinion or is it a bug we have?

**Comment by pariterre** [comment]
@romainmartinez 
Should he fix these issues before or after merging the main PR?

**Comment by romainmartinez** [comment]
Ideally before :)
But it depends on the time we need to invest in this I guess ?
